# Generated by Django 2.1.7 on 2019-03-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecon', '0004_auto_20190309_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_favorite',
            new_name='proc',
        ),
    ]
